version: "3.2"
services:
  influx:
    image: influxdb:1.7-alpine
    ports:
      - 8086:8086
    restart: on-failure
    container_name: docker-influx
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    restart: on-failure
    container_name: docker-loki
